### ISSUE TITLE
Not a bug > Project activity & license

### ISSUE THREAD

**Issue by saurabhnanda** [007design/Formular#1]
I'm halfway through building a custom form generator on top of AngularJS, but would like to replace that with what you've built.
1. I noticed that there haven't been any commits to this project since a year. Have you stopped development on this?
2. The repository does not have a LICENSE. Would it be possible to formally release this under a BSD / MIT license?

**Comment by 007design** [comment]
The repo hasn't been updated because, technically, I'm building this 
for my day job.  I had/have to strip out all identifying information (in 
comments, config files, etc) in order to post it on GitHub.  I have 
tried to talk to my company about licenses but it's just white noise to 
them.  So, go ahead and use what you can.  If you can contribute 
something or even just have a good idea or something I missed, please 
let me know.  I have more recent source, containing a few bug fixes, 
that I can send you but you'll need to ensure that you remove any 
identifying information you run across before publishing anything to the 
net.  Let me know if you are interested and I will send you the updated 
source.
Thanks for your interest.
007

**Comment by saurabhnanda** [comment]
Please send me the updated source. I'm a little worried about lack of a formal license. Please see if it's possible to add that.
